/**
 * GENERATED FILE — do not edit by hand.
 * Run `node scripts/generate-source-catalog.mjs` after changing
 * src/config/feeds.ts or src/config/map-layer-definitions.ts.
 *
 * Every entry below is a source the app actually reads: 572 named
 * RSS/API feeds plus 60 live map layers.
 */

export type SourceGroup =
  | 'wire'
  | 'regional'
  | 'official'
  | 'defense'
  | 'research'
  | 'hazards'
  | 'markets'
  | 'energy'
  | 'tech'
  | 'cyber'
  | 'tracking'
  | 'space'
  | 'positive';

export type SourceKind = 'feed' | 'layer';

/** [name, group, kind] — tuples keep the generated bundle small. */
export type CatalogEntry = readonly [string, SourceGroup, SourceKind];

/** Display order and labels for the group filter. */
export const SOURCE_GROUPS: { id: SourceGroup; label: string; blurb: string }[] = [
  { id: 'wire', label: 'Wires & majors', blurb: 'Global wire services and flagship national outlets.' },
  { id: 'regional', label: 'Regional press', blurb: 'Local and language-native reporting from every region.' },
  { id: 'official', label: 'Government & institutions', blurb: 'Ministries, regulators, sanctions bodies and intl. organisations.' },
  { id: 'defense', label: 'Military & conflict', blurb: 'Defence reporting, conflict trackers and force-posture layers.' },
  { id: 'research', label: 'Research & investigations', blurb: 'Think tanks, OSINT collectives and investigative newsrooms.' },
  { id: 'hazards', label: 'Hazards & climate', blurb: 'Earthquakes, storms, fires, floods and climate monitoring.' },
  { id: 'markets', label: 'Markets & macro', blurb: 'Equities, FX, rates, filings, central banks and macro series.' },
  { id: 'energy', label: 'Energy & commodities', blurb: 'Oil, gas, metals, mining, agriculture and freight.' },
  { id: 'tech', label: 'Technology & AI', blurb: 'Product, research, funding and tech-policy sources.' },
  { id: 'cyber', label: 'Cyber & infrastructure', blurb: 'Advisories, outages, cables, grids and threat activity.' },
  { id: 'tracking', label: 'Aviation & maritime', blurb: 'Live vessel, aircraft and chokepoint tracking layers.' },
  { id: 'space', label: 'Space', blurb: 'Launches, satellites, spaceports and space weather.' },
  { id: 'positive', label: 'Science & positive signals', blurb: 'Research breakthroughs, conservation and human progress.' },
];

export const CATALOG: CatalogEntry[] = [
  ['AI Data Centers', 'cyber', 'layer'],
  ['APT Groups', 'cyber', 'layer'],
  ['AWS Status', 'cyber', 'feed'],
  ['BleepingComputer', 'cyber', 'feed'],
  ['CERT-EU Security Advisories', 'cyber', 'feed'],
  ['CERT-EU Threat Intelligence', 'cyber', 'feed'],
  ['Cloud Outages', 'cyber', 'feed'],
  ['Cyber Threats', 'cyber', 'layer'],
  ['Dark Reading', 'cyber', 'feed'],
  ['GPS Jamming', 'cyber', 'layer'],
  ['Internet Outages', 'cyber', 'layer'],
  ['Krebs Security', 'cyber', 'feed'],
  ['MSRC Security Updates', 'cyber', 'feed'],
  ['NCSC Threat Reports', 'cyber', 'feed'],
  ['Pipelines', 'cyber', 'layer'],
  ['Ransomware.live', 'cyber', 'feed'],
  ['SANS ISC', 'cyber', 'feed'],
  ['Schneier', 'cyber', 'feed'],
  ['The Hacker News', 'cyber', 'feed'],
  ['Undersea Cables', 'cyber', 'layer'],
  ['Armed Conflict Events', 'defense', 'layer'],
  ['Arms Control Assn', 'defense', 'feed'],
  ['Breaking Defense', 'defense', 'feed'],
  ['Bulletin of Atomic Scientists', 'defense', 'feed'],
  ['CFR', 'defense', 'feed'],
  ['Conflict Zones', 'defense', 'layer'],
  ['Defense News', 'defense', 'feed'],
  ['Defense One', 'defense', 'feed'],
  ['Displacement Flows', 'defense', 'layer'],
  ['Gamma Irradiators', 'defense', 'layer'],
  ['gCaptain', 'defense', 'feed'],
  ['GDELT Events', 'defense', 'layer'],
  ['Hudson Institute', 'defense', 'feed'],
  ['IISS', 'defense', 'feed'],
  ['Intel Hotspots', 'defense', 'layer'],
  ['Iran Attacks', 'defense', 'layer'],
  ['ISW', 'defense', 'feed'],
  ['Janes', 'defense', 'feed'],
  ['Long War Journal', 'defense', 'feed'],
  ['Military Activity', 'defense', 'layer'],
  ['Military Bases', 'defense', 'layer'],
  ['Military Times', 'defense', 'feed'],
  ['Modern War Institute', 'defense', 'feed'],
  ['Nuclear Sites', 'defense', 'layer'],
  ['Oryx OSINT', 'defense', 'feed'],
  ['Protests', 'defense', 'layer'],
  ['Sanctions', 'defense', 'layer'],
  ['SIPRI', 'defense', 'feed'],
  ['Small Wars Journal', 'defense', 'feed'],
  ['SOFREP', 'defense', 'feed'],
  ['Task & Purpose', 'defense', 'feed'],
  ['The Cipher Brief', 'defense', 'feed'],
  ['The Soufan Center', 'defense', 'feed'],
  ['The War Zone', 'defense', 'feed'],
  ['UK MOD', 'defense', 'feed'],
  ['USNI News', 'defense', 'feed'],
  ['Agriculture', 'energy', 'feed'],
  ['Aluminum & Zinc', 'energy', 'feed'],
  ['Australian Mining', 'energy', 'feed'],
  ['Benchmark Mineral', 'energy', 'feed'],
  ['BHP News', 'energy', 'feed'],
  ['China Commodity Imports', 'energy', 'feed'],
  ['China Mineral Policy', 'energy', 'feed'],
  ['Cobalt Market', 'energy', 'feed'],
  ['Commodity Ports', 'energy', 'layer'],
  ['Commodity Trading', 'energy', 'feed'],
  ['Copper Market', 'energy', 'feed'],
  ['Critical Mineral Companies', 'energy', 'feed'],
  ['EIA Reports', 'energy', 'feed'],
  ['Energy Intel', 'energy', 'feed'],
  ['ESG in Mining', 'energy', 'feed'],
  ['EV Battery Supply', 'energy', 'feed'],
  ['Freeport & Copper Miners', 'energy', 'feed'],
  ['Glencore & Vale', 'energy', 'feed'],
  ['Gold & Metals', 'energy', 'feed'],
  ['Gold Majors', 'energy', 'feed'],
  ['IEA Critical Minerals', 'energy', 'feed'],
  ['Indonesia Nickel Policy', 'energy', 'feed'],
  ['Iron Ore Market', 'energy', 'feed'],
  ['Lithium Market', 'energy', 'feed'],
  ['LME Metals', 'energy', 'feed'],
  ['Metals Bulletin', 'energy', 'feed'],
  ['Mine Web (SNL)', 'energy', 'feed'],
  ['Mining & Resources', 'energy', 'feed'],
  ['Mining Journal', 'energy', 'feed'],
  ['Mining Regulation', 'energy', 'feed'],
  ['Mining Sites', 'energy', 'layer'],
  ['Mining Technology', 'energy', 'feed'],
  ['Mining Weekly', 'energy', 'feed'],
  ['Natural Gas News', 'energy', 'feed'],
  ['Nickel News', 'energy', 'feed'],
  ['Northern Miner', 'energy', 'feed'],
  ['Nuclear Energy', 'energy', 'feed'],
  ['Oil & Gas', 'energy', 'feed'],
  ['OilPrice.com', 'energy', 'feed'],
  ['OPEC News', 'energy', 'feed'],
  ['Port & Logistics', 'energy', 'feed'],
  ['Processing Plants', 'energy', 'layer'],
  ['Rare Earths News', 'energy', 'feed'],
  ['Resource World', 'energy', 'feed'],
  ['Reuters Energy', 'energy', 'feed'],
  ['Rigzone', 'energy', 'feed'],
  ['Rio Tinto News', 'energy', 'feed'],
  ['Shipping & Freight', 'energy', 'feed'],
  ['Trade Routes', 'energy', 'feed'],
  ['Uranium Market', 'energy', 'feed'],
  ['Arctic Today', 'hazards', 'feed'],
  ['Carbon Brief', 'hazards', 'feed'],
  ['Circle of Blue', 'hazards', 'feed'],
  ['Climate Anomalies', 'hazards', 'layer'],
  ['Climate Home News', 'hazards', 'feed'],
  ['Conservation Optimism', 'hazards', 'feed'],
  ['CrisisWatch', 'hazards', 'feed'],
  ['Day/Night', 'hazards', 'layer'],
  ['Earthquakes', 'hazards', 'layer'],
  ['Fires', 'hazards', 'layer'],
  ['GDACS Alerts', 'hazards', 'feed'],
  ['Global Forest Watch', 'hazards', 'feed'],
  ['GNN Animals', 'hazards', 'feed'],
  ['GNN Earth', 'hazards', 'feed'],
  ['Grist', 'hazards', 'feed'],
  ['High North News', 'hazards', 'feed'],
  ['IAEA', 'hazards', 'feed'],
  ['Inside Climate News', 'hazards', 'feed'],
  ['Mongabay', 'hazards', 'feed'],
  ['Natural Events', 'hazards', 'layer'],
  ['NHC Atlantic GIS', 'hazards', 'feed'],
  ['NHC East Pacific GIS', 'hazards', 'feed'],
  ['Seismic Risk', 'hazards', 'layer'],
  ['The Barents Observer', 'hazards', 'feed'],
  ['UNHCR', 'hazards', 'feed'],
  ['USGS Earthquakes', 'hazards', 'feed'],
  ['USGS Significant Earthquakes', 'hazards', 'feed'],
  ['Water Diplomat', 'hazards', 'feed'],
  ['Weather Alerts', 'hazards', 'layer'],
  ['WHO', 'hazards', 'feed'],
  ['Yale Climate Connections', 'hazards', 'feed'],
  ['Bank Research', 'markets', 'feed'],
  ['BIS Central Bank Speeches', 'markets', 'feed'],
  ['BIS Press Releases', 'markets', 'feed'],
  ['Blockchain Finance', 'markets', 'feed'],
  ['Bloomberg Markets', 'markets', 'feed'],
  ['BoE Watch', 'markets', 'feed'],
  ['BoJ Watch', 'markets', 'feed'],
  ['Bond Market', 'markets', 'feed'],
  ['Central Bank Rates', 'markets', 'feed'],
  ['Central Banks', 'markets', 'layer'],
  ['CNBC', 'markets', 'feed'],
  ['CNBC Markets', 'markets', 'feed'],
  ['CNBC Tech', 'markets', 'feed'],
  ['CoinDesk', 'markets', 'feed'],
  ['Cointelegraph', 'markets', 'feed'],
  ['Commodity Futures', 'markets', 'feed'],
  ['Commodity Hubs', 'markets', 'layer'],
  ['Corporate Bonds', 'markets', 'feed'],
  ['Critical Minerals', 'markets', 'layer'],
  ['Crypto News', 'markets', 'feed'],
  ['DeFi News', 'markets', 'feed'],
  ['Dollar Watch', 'markets', 'feed'],
  ['Earnings Reports', 'markets', 'feed'],
  ['ECB Watch', 'markets', 'feed'],
  ['Economic Centers', 'markets', 'layer'],
  ['Economic Data', 'markets', 'feed'],
  ['FAO GIEWS', 'markets', 'feed'],
  ['FAO News', 'markets', 'feed'],
  ['Financial Centers', 'markets', 'layer'],
  ['Financial Times', 'markets', 'feed'],
  ['Fintech News', 'markets', 'feed'],
  ['Forex News', 'markets', 'feed'],
  ['Futures Trading', 'markets', 'feed'],
  ['GCC Investments', 'markets', 'layer'],
  ['Global Central Banks', 'markets', 'feed'],
  ['Hedge Fund News', 'markets', 'feed'],
  ['Housing Market', 'markets', 'feed'],
  ['Investing.com News', 'markets', 'feed'],
  ['IPO News', 'markets', 'feed'],
  ['M&A News', 'markets', 'feed'],
  ['Market Outlook', 'markets', 'feed'],
  ['Market Performance', 'markets', 'layer'],
  ['MarketWatch', 'markets', 'feed'],
  ['MarketWatch Tech', 'markets', 'feed'],
  ['Options Market', 'markets', 'feed'],
  ['PBoC Watch', 'markets', 'feed'],
  ['Prediction Markets', 'markets', 'layer'],
  ['Private Equity', 'markets', 'feed'],
  ['Renaissance IPO', 'markets', 'feed'],
  ['Reuters Business', 'markets', 'feed'],
  ['Reuters Markets', 'markets', 'feed'],
  ['Risk & Volatility', 'markets', 'feed'],
  ['SC 13D/G', 'markets', 'feed'],
  ['SEC 10-K', 'markets', 'feed'],
  ['SEC 10-Q', 'markets', 'feed'],
  ['SEC 13F Filings', 'markets', 'feed'],
  ['SEC 13F-HR', 'markets', 'feed'],
  ['SEC 8-K', 'markets', 'feed'],
  ['SEC All Filings', 'markets', 'feed'],
  ['SEC DEF 14A', 'markets', 'feed'],
  ['SEC Filings', 'markets', 'feed'],
  ['SEC Form 4', 'markets', 'feed'],
  ['SEC S-1', 'markets', 'feed'],
  ['Seed & Pre-Seed', 'markets', 'feed'],
  ['Seeking Alpha', 'markets', 'feed'],
  ['Seeking Alpha Metals', 'markets', 'feed'],
  ['Seeking Alpha Tech', 'markets', 'feed'],
  ['Sovereign Wealth', 'markets', 'feed'],
  ['Startup Funding', 'markets', 'feed'],
  ['Stock Exchanges', 'markets', 'layer'],
  ['Tariff Barriers', 'markets', 'layer'],
  ['Tech IPO News', 'markets', 'feed'],
  ['The Block', 'markets', 'feed'],
  ['Trade & Tariffs', 'markets', 'feed'],
  ['Trading Tech', 'markets', 'feed'],
  ['Treasury Watch', 'markets', 'feed'],
  ['VC News', 'markets', 'feed'],
  ['WTO Latest News', 'markets', 'feed'],
  ['Yahoo Finance', 'markets', 'feed'],
  ['Yahoo Finance Commodities', 'markets', 'feed'],
  ['Banking Rules', 'official', 'feed'],
  ['CDC', 'official', 'feed'],
  ['CII Instability', 'official', 'layer'],
  ['CISA', 'official', 'feed'],
  ['Crypto Regulation', 'official', 'feed'],
  ['Democracy Index', 'official', 'layer'],
  ['DHS', 'official', 'feed'],
  ['DOJ', 'official', 'feed'],
  ['Elections', 'official', 'layer'],
  ['Federal Reserve', 'official', 'feed'],
  ['FEMA', 'official', 'feed'],
  ['Financial Regulation', 'official', 'feed'],
  ['Governance Quality', 'official', 'layer'],
  ['InfoMigrants', 'official', 'feed'],
  ['IOM News', 'official', 'feed'],
  ['Migration Policy Inst', 'official', 'feed'],
  ['OFAC Recent Actions', 'official', 'feed'],
  ['Pentagon', 'official', 'feed'],
  ['Sanctions & Export Controls', 'official', 'feed'],
  ['SEC', 'official', 'feed'],
  ['State Dept', 'official', 'feed'],
  ['Treasury', 'official', 'feed'],
  ['UN News', 'official', 'feed'],
  ['White House', 'official', 'feed'],
  ['Acts of Kindness', 'positive', 'layer'],
  ['Clean Energy', 'positive', 'layer'],
  ['DailyGood', 'positive', 'feed'],
  ['GNN Health', 'positive', 'feed'],
  ['GNN Heroes', 'positive', 'feed'],
  ['GNN Heroes Spotlight', 'positive', 'feed'],
  ['GNN Science', 'positive', 'feed'],
  ['Good Good Good', 'positive', 'feed'],
  ['GOOD Magazine', 'positive', 'feed'],
  ['Good News Network', 'positive', 'feed'],
  ['Greater Good (Berkeley)', 'positive', 'feed'],
  ['Human Progress', 'positive', 'feed'],
  ['Live Science', 'positive', 'feed'],
  ['My Modern Met', 'positive', 'feed'],
  ['Nature News', 'positive', 'feed'],
  ['New Scientist', 'positive', 'feed'],
  ['Optimist Daily', 'positive', 'feed'],
  ['Positive Events', 'positive', 'layer'],
  ['Positive.News', 'positive', 'feed'],
  ['Reasons to be Cheerful', 'positive', 'feed'],
  ['ScienceDaily', 'positive', 'feed'],
  ['Shareable', 'positive', 'feed'],
  ['Singularity Hub', 'positive', 'feed'],
  ['Species Recovery', 'positive', 'layer'],
  ['Sunny Skyz', 'positive', 'feed'],
  ['The Better India', 'positive', 'feed'],
  ['Upworthy', 'positive', 'feed'],
  ['World Happiness', 'positive', 'layer'],
  ['Yes! Magazine', 'positive', 'feed'],
  ['24.kg', 'regional', 'feed'],
  ['ABC News Australia', 'regional', 'feed'],
  ['Africa News', 'regional', 'feed'],
  ['Africanews', 'regional', 'feed'],
  ['Al Arabiya', 'regional', 'feed'],
  ['Al Jazeera', 'regional', 'feed'],
  ['Al-Monitor', 'regional', 'feed'],
  ['ANSA', 'regional', 'feed'],
  ['AP Mexico', 'regional', 'feed'],
  ['Arab News', 'regional', 'feed'],
  ['Arabian Business', 'regional', 'feed'],
  ['Asahi Shimbun', 'regional', 'feed'],
  ['Asharq Business', 'regional', 'feed'],
  ['Asharq News', 'regional', 'feed'],
  ['Asia News', 'regional', 'feed'],
  ['Asia-Plus', 'regional', 'feed'],
  ['AzerNews', 'regional', 'feed'],
  ['Balkan Insight', 'regional', 'feed'],
  ['Bangkok Post', 'regional', 'feed'],
  ['BBC Africa', 'regional', 'feed'],
  ['BBC Afrique', 'regional', 'feed'],
  ['BBC Asia', 'regional', 'feed'],
  ['BBC Latin America', 'regional', 'feed'],
  ['BBC Middle East', 'regional', 'feed'],
  ['BBC Mundo', 'regional', 'feed'],
  ['BBC Persian', 'regional', 'feed'],
  ['BBC Russian', 'regional', 'feed'],
  ['BBC Turkce', 'regional', 'feed'],
  ['Bild', 'regional', 'feed'],
  ['BIRN', 'regional', 'feed'],
  ['Brasil Paralelo', 'regional', 'feed'],
  ['Caribbean News Now', 'regional', 'feed'],
  ['CBC News', 'regional', 'feed'],
  ['Channels TV', 'regional', 'feed'],
  ['Chosun Ilbo', 'regional', 'feed'],
  ['Civil.ge', 'regional', 'feed'],
  ['CivilNet', 'regional', 'feed'],
  ['Clarín', 'regional', 'feed'],
  ['CNA', 'regional', 'feed'],
  ['Colombo Page', 'regional', 'feed'],
  ['Corriere della Sera', 'regional', 'feed'],
  ['Council EU Press', 'regional', 'feed'],
  ['CTV News', 'regional', 'feed'],
  ['Dagens Nyheter', 'regional', 'feed'],
  ['Daily Maverick', 'regional', 'feed'],
  ['Daily Trust', 'regional', 'feed'],
  ['Dawn', 'regional', 'feed'],
  ['De Telegraaf', 'regional', 'feed'],
  ['Der Spiegel', 'regional', 'feed'],
  ['Dhaka Tribune', 'regional', 'feed'],
  ['Die Zeit', 'regional', 'feed'],
  ['DR News', 'regional', 'feed'],
  ['DW News', 'regional', 'feed'],
  ['DW Turkish', 'regional', 'feed'],
  ['ECB Press', 'regional', 'feed'],
  ['El Mundo', 'regional', 'feed'],
  ['El País', 'regional', 'feed'],
  ['El Tiempo', 'regional', 'feed'],
  ['El Universo', 'regional', 'feed'],
  ['Eurasianet', 'regional', 'feed'],
  ['EuroNews', 'regional', 'feed'],
  ['Fars News', 'regional', 'feed'],
  ['Fiji Times', 'regional', 'feed'],
  ['Folha de S.Paulo', 'regional', 'feed'],
  ['France 24', 'regional', 'feed'],
  ['France 24 LatAm', 'regional', 'feed'],
  ['Globe and Mail', 'regional', 'feed'],
  ['Guardian Americas', 'regional', 'feed'],
  ['Guardian Australia', 'regional', 'feed'],
  ['Guardian ME', 'regional', 'feed'],
  ['Gulf FDI', 'regional', 'feed'],
  ['Gulf Investments', 'regional', 'feed'],
  ['Haaretz', 'regional', 'feed'],
  ['Hurriyet', 'regional', 'feed'],
  ['iefimerida', 'regional', 'feed'],
  ['in.gr', 'regional', 'feed'],
  ['India News Network', 'regional', 'feed'],
  ['Indian Express', 'regional', 'feed'],
  ['Infobae Americas', 'regional', 'feed'],
  ['InSight Crime', 'regional', 'feed'],
  ['Iran International', 'regional', 'feed'],
  ['Island Times (Palau)', 'regional', 'feed'],
  ['Jamaica Gleaner', 'regional', 'feed'],
  ['Japan Today', 'regional', 'feed'],
  ['Jeune Afrique', 'regional', 'feed'],
  ['Kathimerini', 'regional', 'feed'],
  ['Kathmandu Post', 'regional', 'feed'],
  ['Kyiv Independent', 'regional', 'feed'],
  ['La Silla Vacía', 'regional', 'feed'],
  ['Latin America', 'regional', 'feed'],
  ['Le Monde', 'regional', 'feed'],
  ['LiveMint', 'regional', 'feed'],
  ['Mail & Guardian', 'regional', 'feed'],
  ['Meduza', 'regional', 'feed'],
  ['MercoPress LatAm', 'regional', 'feed'],
  ['Mexico News Daily', 'regional', 'feed'],
  ['Mexico Security', 'regional', 'feed'],
  ['Middle East Eye', 'regional', 'feed'],
  ['MIIT (China)', 'regional', 'feed'],
  ['MOFCOM (China)', 'regional', 'feed'],
  ['Moscow Times', 'regional', 'feed'],
  ['Myanmar Now', 'regional', 'feed'],
  ['Naftemporiki', 'regional', 'feed'],
  ['NATO News', 'regional', 'feed'],
  ['NDTV', 'regional', 'feed'],
  ['News24', 'regional', 'feed'],
  ['Nikkei Asia', 'regional', 'feed'],
  ['NOS Nieuws', 'regional', 'feed'],
  ['Novaya Gazeta Europe', 'regional', 'feed'],
  ['NRC', 'regional', 'feed'],
  ['NRK News', 'regional', 'feed'],
  ['O Globo', 'regional', 'feed'],
  ['OC Media', 'regional', 'feed'],
  ['Oman Observer', 'regional', 'feed'],
  ['Polsat News', 'regional', 'feed'],
  ['Premium Times', 'regional', 'feed'],
  ['Primicias', 'regional', 'feed'],
  ['Proto Thema', 'regional', 'feed'],
  ['PTI', 'regional', 'feed'],
  ['Rappler', 'regional', 'feed'],
  ['Repubblica', 'regional', 'feed'],
  ['Reuters Asia', 'regional', 'feed'],
  ['Reuters LatAm', 'regional', 'feed'],
  ['RFE/RL Central Asia', 'regional', 'feed'],
  ['RNZ Pacific', 'regional', 'feed'],
  ['RT', 'regional', 'feed'],
  ['RT Russia', 'regional', 'feed'],
  ['Rudaw', 'regional', 'feed'],
  ['RUV News', 'regional', 'feed'],
  ['Rzeczpospolita', 'regional', 'feed'],
  ['Sahel Crisis', 'regional', 'feed'],
  ['South China Morning Post', 'regional', 'feed'],
  ['Svenska Dagbladet', 'regional', 'feed'],
  ['SVT Nyheter', 'regional', 'feed'],
  ['Tagesschau', 'regional', 'feed'],
  ['TASS', 'regional', 'feed'],
  ['Thai PBS', 'regional', 'feed'],
  ['The Astana Times', 'regional', 'feed'],
  ['The Daily Star', 'regional', 'feed'],
  ['The Diplomat', 'regional', 'feed'],
  ['The Hindu', 'regional', 'feed'],
  ['The Irrawaddy', 'regional', 'feed'],
  ['The National', 'regional', 'feed'],
  ['ThisDay', 'regional', 'feed'],
  ['Times of Oman', 'regional', 'feed'],
  ['Toronto Star', 'regional', 'feed'],
  ['Total Slovenia News', 'regional', 'feed'],
  ['TRT World', 'regional', 'feed'],
  ['Tuoi Tre News', 'regional', 'feed'],
  ['TVN24', 'regional', 'feed'],
  ['Vanguard Nigeria', 'regional', 'feed'],
  ['Vision 2030', 'regional', 'feed'],
  ['VnExpress', 'regional', 'feed'],
  ['Xinhua', 'regional', 'feed'],
  ['YLE News', 'regional', 'feed'],
  ['Yonhap News', 'regional', 'feed'],
  ['AEI', 'research', 'feed'],
  ['AI Now Institute', 'research', 'feed'],
  ['Amnesty International', 'research', 'feed'],
  ['Asia Pacific Tech', 'research', 'feed'],
  ['Atlantic Council', 'research', 'feed'],
  ['Bellingcat', 'research', 'feed'],
  ['Brookings', 'research', 'feed'],
  ['Brookings Tech', 'research', 'feed'],
  ['Carnegie', 'research', 'feed'],
  ['Chatham House', 'research', 'feed'],
  ['Chatham House Tech', 'research', 'feed'],
  ['China Tech Analysis', 'research', 'feed'],
  ['CNAS', 'research', 'feed'],
  ['Correctiv', 'research', 'feed'],
  ['CSIS', 'research', 'feed'],
  ['CSIS Tech', 'research', 'feed'],
  ['DFRLab', 'research', 'feed'],
  ['DigiChina', 'research', 'feed'],
  ['ECFR', 'research', 'feed'],
  ['EU ISS', 'research', 'feed'],
  ['EU Tech Policy', 'research', 'feed'],
  ['FAS', 'research', 'feed'],
  ['Foreign Affairs', 'research', 'feed'],
  ['Foreign Policy', 'research', 'feed'],
  ['FPRI', 'research', 'feed'],
  ['GITOC', 'research', 'feed'],
  ['GMF', 'research', 'feed'],
  ['Human Rights Watch', 'research', 'feed'],
  ['Intl Justice Monitor', 'research', 'feed'],
  ['ISEAS (Singapore)', 'research', 'feed'],
  ['Jamestown', 'research', 'feed'],
  ['Just Security', 'research', 'feed'],
  ['Lighthouse Reports', 'research', 'feed'],
  ['Lowy Institute', 'research', 'feed'],
  ['Middle East Institute', 'research', 'feed'],
  ['MIT Tech Policy', 'research', 'feed'],
  ['NTI', 'research', 'feed'],
  ['OCCRP', 'research', 'feed'],
  ['OECD Digital', 'research', 'feed'],
  ['ORF Tech (India)', 'research', 'feed'],
  ['RAND', 'research', 'feed'],
  ['Responsible Statecraft', 'research', 'feed'],
  ['RIETI (Japan)', 'research', 'feed'],
  ['RUSI', 'research', 'feed'],
  ['Stanford HAI', 'research', 'feed'],
  ['Stimson Center', 'research', 'feed'],
  ['The Sentry', 'research', 'feed'],
  ['Transparency International', 'research', 'feed'],
  ['VSquare', 'research', 'feed'],
  ['War on the Rocks', 'research', 'feed'],
  ['Wilson Center', 'research', 'feed'],
  ['Ars Technica Science', 'space', 'feed'],
  ['ESA News', 'space', 'feed'],
  ['NASA Breaking News', 'space', 'feed'],
  ['NASASpaceflight', 'space', 'feed'],
  ['Satellites', 'space', 'layer'],
  ['SpaceNews', 'space', 'feed'],
  ['Spaceports', 'space', 'layer'],
  ['20VC Episodes', 'tech', 'feed'],
  ['36Kr English', 'tech', 'feed'],
  ['500 Global News', 'tech', 'feed'],
  ['a16z Blog', 'tech', 'feed'],
  ['a16z Insights', 'tech', 'feed'],
  ['Accelerators', 'tech', 'layer'],
  ['Acquired Episodes', 'tech', 'feed'],
  ['Africa Startups', 'tech', 'feed'],
  ['Africa Tech News', 'tech', 'feed'],
  ['AI Interviews', 'tech', 'feed'],
  ['AI News', 'tech', 'feed'],
  ['AI Podcasts', 'tech', 'feed'],
  ['AI Regulation', 'tech', 'feed'],
  ['AI Weekly', 'tech', 'feed'],
  ['All-In Podcast', 'tech', 'feed'],
  ['AngelList News', 'tech', 'feed'],
  ['Anthropic News', 'tech', 'feed'],
  ['Ars Technica', 'tech', 'feed'],
  ['ArXiv AI', 'tech', 'feed'],
  ['ArXiv ML', 'tech', 'feed'],
  ['Asia VC News', 'tech', 'feed'],
  ['Brazil Tech', 'tech', 'feed'],
  ['CB Insights', 'tech', 'feed'],
  ['CB Insights Unicorn', 'tech', 'feed'],
  ['Changelog', 'tech', 'feed'],
  ['China Startups', 'tech', 'feed'],
  ['China Tech Giants', 'tech', 'feed'],
  ['China Tech Policy', 'tech', 'feed'],
  ['Cloud Regions', 'tech', 'layer'],
  ['Crunchbase News', 'tech', 'feed'],
  ['Decacorn News', 'tech', 'feed'],
  ['Demo Day News', 'tech', 'feed'],
  ['Dev Events', 'tech', 'feed'],
  ['Dev.to', 'tech', 'feed'],
  ['DevOps.com', 'tech', 'feed'],
  ['EFF News', 'tech', 'feed'],
  ['Engadget', 'tech', 'feed'],
  ['EU Commission Digital', 'tech', 'feed'],
  ['EU Digital Policy', 'tech', 'feed'],
  ['EU Startups', 'tech', 'feed'],
  ['Euractiv Digital', 'tech', 'feed'],
  ['Fast Company', 'tech', 'feed'],
  ['FinTech LATAM', 'tech', 'feed'],
  ['Fortune Term Sheet', 'tech', 'feed'],
  ['FwdStart Newsletter', 'tech', 'feed'],
  ['GitHub Blog', 'tech', 'feed'],
  ['GitHub Trending', 'tech', 'feed'],
  ['Hacker News', 'tech', 'feed'],
  ['Hard Fork (NYT)', 'tech', 'feed'],
  ['How I Built This', 'tech', 'feed'],
  ['Inc42 (India)', 'tech', 'feed'],
  ['India Startups', 'tech', 'feed'],
  ['India Tech News', 'tech', 'feed'],
  ['India Tech Policy', 'tech', 'feed'],
  ['Indonesia Tech', 'tech', 'feed'],
  ['InfoQ', 'tech', 'feed'],
  ['Japan Startups', 'tech', 'feed'],
  ['Japan Tech News', 'tech', 'feed'],
  ['Korea Startups', 'tech', 'feed'],
  ['Korea Tech News', 'tech', 'feed'],
  ['KrASIA', 'tech', 'feed'],
  ['LATAM Startups', 'tech', 'feed'],
  ['LAVCA (LATAM)', 'tech', 'feed'],
  ['Layoffs News', 'tech', 'feed'],
  ['Layoffs.fyi', 'tech', 'feed'],
  ['Lenny\'s Newsletter', 'tech', 'feed'],
  ['Lex Fridman Tech', 'tech', 'feed'],
  ['Lobsters', 'tech', 'feed'],
  ['Masters of Scale', 'tech', 'feed'],
  ['MENA Startups', 'tech', 'feed'],
  ['MENA Tech News', 'tech', 'feed'],
  ['MIT Research', 'tech', 'feed'],
  ['MIT Tech Review', 'tech', 'feed'],
  ['MIT Tech Review AI', 'tech', 'feed'],
  ['New Unicorns', 'tech', 'feed'],
  ['Nikkei Tech', 'tech', 'feed'],
  ['Open Source News', 'tech', 'feed'],
  ['OpenAI News', 'tech', 'feed'],
  ['Paul Graham Essays', 'tech', 'feed'],
  ['PitchBook News', 'tech', 'feed'],
  ['Pivot Podcast', 'tech', 'feed'],
  ['Politico Tech', 'tech', 'feed'],
  ['Product Hunt', 'tech', 'feed'],
  ['SaaStr', 'tech', 'feed'],
  ['SEA Startups', 'tech', 'feed'],
  ['SEA Tech News', 'tech', 'feed'],
  ['SemiAnalysis', 'tech', 'feed'],
  ['Semiconductor News', 'tech', 'feed'],
  ['Sequoia Blog', 'tech', 'feed'],
  ['Show HN', 'tech', 'feed'],
  ['Sifted (Europe)', 'tech', 'feed'],
  ['Startup Hubs', 'tech', 'layer'],
  ['Startup School', 'tech', 'feed'],
  ['Startups LATAM', 'tech', 'feed'],
  ['Stratechery', 'tech', 'feed'],
  ['Taiwan Tech', 'tech', 'feed'],
  ['Tech Antitrust', 'tech', 'feed'],
  ['Tech Events', 'tech', 'layer'],
  ['Tech HQs', 'tech', 'layer'],
  ['Tech in Asia', 'tech', 'feed'],
  ['Tech Newsletters', 'tech', 'feed'],
  ['Tech.eu', 'tech', 'feed'],
  ['TechCabal (Africa)', 'tech', 'feed'],
  ['TechCrunch', 'tech', 'feed'],
  ['TechCrunch Layoffs', 'tech', 'feed'],
  ['TechCrunch Startups', 'tech', 'feed'],
  ['TechCrunch Venture', 'tech', 'feed'],
  ['TechMeme', 'tech', 'feed'],
  ['Techstars News', 'tech', 'feed'],
  ['The Information', 'tech', 'feed'],
  ['The New Stack', 'tech', 'feed'],
  ['The Next Web', 'tech', 'feed'],
  ['The Verge', 'tech', 'feed'],
  ['The Verge AI', 'tech', 'feed'],
  ['TWIST Episodes', 'tech', 'feed'],
  ['UK Tech Policy', 'tech', 'feed'],
  ['Unicorn News', 'tech', 'feed'],
  ['VC Insights', 'tech', 'feed'],
  ['VentureBeat', 'tech', 'feed'],
  ['VentureBeat AI', 'tech', 'feed'],
  ['Verge Shows', 'tech', 'feed'],
  ['Vietnam Tech', 'tech', 'feed'],
  ['Y Combinator Blog', 'tech', 'feed'],
  ['YC Launches', 'tech', 'feed'],
  ['YourStory', 'tech', 'feed'],
  ['ZDNet', 'tech', 'feed'],
  ['Flight Delays', 'tracking', 'layer'],
  ['Nav Warnings', 'tracking', 'layer'],
  ['Ship Traffic', 'tracking', 'layer'],
  ['Strategic Waterways', 'tracking', 'layer'],
  ['Trade Routes', 'tracking', 'layer'],
  ['ABC News', 'wire', 'feed'],
  ['AP News', 'wire', 'feed'],
  ['Axios', 'wire', 'feed'],
  ['BBC World', 'wire', 'feed'],
  ['CBS News', 'wire', 'feed'],
  ['CNN World', 'wire', 'feed'],
  ['Fox News', 'wire', 'feed'],
  ['Guardian World', 'wire', 'feed'],
  ['NBC News', 'wire', 'feed'],
  ['NPR News', 'wire', 'feed'],
  ['PBS NewsHour', 'wire', 'feed'],
  ['Politico', 'wire', 'feed'],
  ['Reuters US', 'wire', 'feed'],
  ['Reuters World', 'wire', 'feed'],
  ['The Hill', 'wire', 'feed'],
  ['Trump - Truth Social', 'wire', 'feed'],
  ['Wall Street Journal', 'wire', 'feed'],
];

export const CATALOG_FEED_COUNT = 572;
export const CATALOG_LAYER_COUNT = 60;
