// ============================================================================
// ELECTIONS — Seed Data (Phase 1)
// ============================================================================
// Real upcoming 2025-2026 elections. Will be replaced by API data in Phase 2+.

import type { Election } from '@/types/elections';

const PARTY_COLORS: Record<string, string> = {
  Democratic: '#3b82f6',
  Republican: '#ef4444',
  Independent: '#a855f7',
  Green: '#22c55e',
  Libertarian: '#f59e0b',
  Labour: '#dc2626',
  Conservative: '#2563eb',
  Liberal: '#f97316',
  AfD: '#1d4ed8',
  SPD: '#dc2626',
  CDU: '#111827',
  FDP: '#eab308',
  Greens: '#16a34a',
  BJP: '#f97316',
  INC: '#3b82f6',
  AAP: '#22c55e',
  Other: '#6b7280',
};

const pc = (key: string): string => PARTY_COLORS[key] ?? '#6b7280';

export const SEED_ELECTIONS: Election[] = [
  // ── US Federal ──────────────────────────────────────────────────────────
  {
    id: 'us-2026-senate-ca',
    name: '2026 California Senate',
    country: 'US',
    countryName: 'United States',
    level: 'federal',
    office: 'Senate',
    district: 'Statewide',
    type: 'general',
    date: '2026-11-03',
    status: 'upcoming',
    description: 'Open seat — Senator Alex Padilla not seeking re-election.',
    candidates: [
      {
        id: 'cand-ca-1',
        name: 'Adam Schiff',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
        bio: 'U.S. Representative for CA-30, former lead impeachment manager.',
        fundingTotal: 28_500_000,
        fundingSpent: 12_300_000,
        policies: [
          { id: 'p1', category: 'healthcare', position: 'Expand ACA subsidies, public option' },
          { id: 'p2', category: 'climate', position: 'Green New Deal framework, carbon tax' },
          { id: 'p3', category: 'immigration', position: 'Path to citizenship, border tech investment' },
        ],
        topDonors: [
          { name: "Emily's List", type: 'pac', amount: 2_500_000 },
          { name: 'Trial Lawyers Assoc.', type: 'organization', amount: 1_800_000 },
        ],
      },
      {
        id: 'cand-ca-2',
        name: 'Steve Garvey',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: false,
      },
    ],
  },
  {
    id: 'us-2026-senate-fl',
    name: '2026 Florida Senate',
    country: 'US',
    countryName: 'United States',
    level: 'federal',
    office: 'Senate',
    district: 'Statewide',
    type: 'general',
    date: '2026-11-03',
    status: 'upcoming',
    candidates: [
      {
        id: 'cand-fl-1',
        name: 'Rick Scott',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: true,
        fundingTotal: 42_000_000,
        fundingSpent: 18_500_000,
      },
      {
        id: 'cand-fl-2',
        name: 'Debbie Mucarsel-Powell',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
        fundingTotal: 15_200_000,
        fundingSpent: 8_100_000,
      },
    ],
  },
  {
    id: 'us-2026-senate-tx',
    name: '2026 Texas Senate',
    country: 'US',
    countryName: 'United States',
    level: 'federal',
    office: 'Senate',
    district: 'Statewide',
    type: 'general',
    date: '2026-11-03',
    status: 'upcoming',
    candidates: [
      {
        id: 'cand-tx-1',
        name: 'Ted Cruz',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: true,
        fundingTotal: 38_700_000,
        fundingSpent: 22_100_000,
      },
      {
        id: 'cand-tx-2',
        name: 'Colin Allred',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
        fundingTotal: 12_400_000,
        fundingSpent: 6_800_000,
      },
    ],
  },
  {
    id: 'us-2025-governor-va',
    name: '2025 Virginia Governor',
    country: 'US',
    countryName: 'United States',
    level: 'state',
    office: 'Governor',
    district: 'Statewide',
    type: 'general',
    date: '2025-11-04',
    status: 'completed',
    candidates: [
      {
        id: 'cand-va-1',
        name: 'Abigail Spanberger',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
      },
      {
        id: 'cand-va-2',
        name: 'Winsome Earle-Sears',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: false,
      },
    ],
    results: [
      { candidateId: 'cand-va-1', votes: 1_520_000, percentage: 53.2, winner: true },
      { candidateId: 'cand-va-2', votes: 1_280_000, percentage: 44.8, winner: false },
    ],
  },
  {
    id: 'us-2025-governor-nj',
    name: '2025 New Jersey Governor',
    country: 'US',
    countryName: 'United States',
    level: 'state',
    office: 'Governor',
    district: 'Statewide',
    type: 'general',
    date: '2025-11-04',
    status: 'completed',
    candidates: [
      {
        id: 'cand-nj-1',
        name: 'Mikie Sherrill',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
      },
      {
        id: 'cand-nj-2',
        name: 'Jack Ciattarelli',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: false,
      },
    ],
    results: [
      { candidateId: 'cand-nj-1', votes: 1_850_000, percentage: 55.1, winner: true },
      { candidateId: 'cand-nj-2', votes: 1_420_000, percentage: 42.4, winner: false },
    ],
  },
  {
    id: 'us-2026-house-ny-17',
    name: '2026 NY-17 House',
    country: 'US',
    countryName: 'United States',
    level: 'federal',
    office: 'House',
    district: 'District 17',
    type: 'general',
    date: '2026-11-03',
    status: 'upcoming',
    description: 'Swing district in Westchester County.',
    candidates: [
      {
        id: 'cand-ny17-1',
        name: 'Michael Lawler',
        party: 'Republican',
        partyColor: pc('Republican'),
        incumbency: true,
        fundingTotal: 5_200_000,
      },
      {
        id: 'cand-ny17-2',
        name: 'TBD',
        party: 'Democratic',
        partyColor: pc('Democratic'),
        incumbency: false,
      },
    ],
  },
  {
    id: 'uk-2024-general',
    name: '2024 UK General Election',
    country: 'GB',
    countryName: 'United Kingdom',
    level: 'national',
    office: 'Parliament',
    district: 'Statewide',
    type: 'general',
    date: '2024-07-04',
    status: 'completed',
    description: 'Labour landslide — 412 seats, ending 14 years of Conservative rule.',
    candidates: [
      {
        id: 'cand-uk-1',
        name: 'Keir Starmer (Labour)',
        party: 'Labour',
        partyColor: pc('Labour'),
        incumbency: false,
      },
      {
        id: 'cand-uk-2',
        name: 'Rishi Sunak (Conservative)',
        party: 'Conservative',
        partyColor: pc('Conservative'),
        incumbency: true,
      },
      {
        id: 'cand-uk-3',
        name: 'Ed Davey (Lib Dem)',
        party: 'Liberal',
        partyColor: pc('Liberal'),
        incumbency: false,
      },
    ],
    results: [
      { candidateId: 'cand-uk-1', votes: 9_705_000, percentage: 33.7, winner: true },
      { candidateId: 'cand-uk-2', votes: 6_803_000, percentage: 23.7, winner: false },
      { candidateId: 'cand-uk-3', votes: 3_507_000, percentage: 12.2, winner: false },
    ],
  },
  {
    id: 'de-2025-federal',
    name: '2025 German Federal Election',
    country: 'DE',
    countryName: 'Germany',
    level: 'national',
    office: 'Bundestag',
    district: 'Statewide',
    type: 'general',
    date: '2025-02-23',
    status: 'completed',
    description: 'CDU/CSU victory — Friedrich Merz set to become Chancellor.',
    candidates: [
      {
        id: 'cand-de-1',
        name: 'Friedrich Merz (CDU)',
        party: 'CDU',
        partyColor: pc('CDU'),
        incumbency: false,
      },
      {
        id: 'cand-de-2',
        name: 'Olaf Scholz (SPD)',
        party: 'SPD',
        partyColor: pc('SPD'),
        incumbency: true,
      },
      {
        id: 'cand-de-3',
        name: 'Alice Weidel (AfD)',
        party: 'AfD',
        partyColor: pc('AfD'),
        incumbency: false,
      },
    ],
    results: [
      { candidateId: 'cand-de-1', votes: 12_300_000, percentage: 28.6, winner: true },
      { candidateId: 'cand-de-2', votes: 7_800_000, percentage: 16.4, winner: false },
      { candidateId: 'cand-de-3', votes: 8_900_000, percentage: 20.8, winner: false },
    ],
  },
  {
    id: 'in-2024-general',
    name: '2024 Indian General Election',
    country: 'IN',
    countryName: 'India',
    level: 'national',
    office: 'Lok Sabha',
    district: 'Statewide',
    type: 'general',
    date: '2024-06-01',
    status: 'completed',
    description: 'NDA coalition wins majority — Modi third term, but BJP loses single-party majority.',
    candidates: [
      {
        id: 'cand-in-1',
        name: 'Narendra Modi (BJP/NDA)',
        party: 'BJP',
        partyColor: pc('BJP'),
        incumbency: true,
      },
      {
        id: 'cand-in-2',
        name: 'INDIA Alliance',
        party: 'INC',
        partyColor: pc('INC'),
        incumbency: false,
      },
    ],
    results: [
      { candidateId: 'cand-in-1', votes: 234_000_000, percentage: 43.6, winner: true },
      { candidateId: 'cand-in-2', votes: 186_000_000, percentage: 34.8, winner: false },
    ],
  },
];

// ── Geo results for map choropleth (US Senate races) ──────────────────────
export const SEED_ELECTION_GEO: Array<{ electionId: string; geo: import('@/types/elections').ElectionGeoResult[] }> = [
  {
    electionId: 'us-2026-senate-ca',
    geo: [
      {
        electionId: 'us-2026-senate-ca',
        region: 'California',
        regionCode: 'US-CA',
        lat: 36.7783,
        lon: -119.4179,
        winner: 'Democratic',
        winnerColor: pc('Democratic'),
        results: [
          { party: 'Democratic', partyColor: pc('Democratic'), percentage: 52, votes: 8_200_000 },
          { party: 'Republican', partyColor: pc('Republican'), percentage: 44, votes: 6_900_000 },
          { party: 'Other', partyColor: pc('Other'), percentage: 4, votes: 630_000 },
        ],
      },
    ],
  },
];
