export interface SectorConstituent {
  symbol: string;
  name: string;
}

export interface SectorMeta {
  etf: string;
  fullName: string;
  constituents: SectorConstituent[];
}

export const SECTOR_CONSTITUENTS: Record<string, SectorMeta> = {
  XLK: {
    etf: 'XLK',
    fullName: 'Technology',
    constituents: [
      { symbol: 'AAPL', name: 'Apple' },
      { symbol: 'MSFT', name: 'Microsoft' },
      { symbol: 'NVDA', name: 'NVIDIA' },
      { symbol: 'AVGO', name: 'Broadcom' },
      { symbol: 'ORCL', name: 'Oracle' },
      { symbol: 'CRM', name: 'Salesforce' },
      { symbol: 'ADBE', name: 'Adobe' },
      { symbol: 'AMD', name: 'AMD' },
      { symbol: 'INTC', name: 'Intel' },
      { symbol: 'QCOM', name: 'Qualcomm' },
      { symbol: 'IBM', name: 'IBM' },
      { symbol: 'NOW', name: 'ServiceNow' },
      { symbol: 'PANW', name: 'Palo Alto Networks' },
      { symbol: 'ADP', name: 'ADP' },
      { symbol: 'ANET', name: 'Arista Networks' },
    ],
  },
  XLF: {
    etf: 'XLF',
    fullName: 'Financials',
    constituents: [
      { symbol: 'BRK-B', name: 'Berkshire Hathaway' },
      { symbol: 'JPM', name: 'JPMorgan Chase' },
      { symbol: 'V', name: 'Visa' },
      { symbol: 'MA', name: 'Mastercard' },
      { symbol: 'BAC', name: 'Bank of America' },
      { symbol: 'WFC', name: 'Wells Fargo' },
      { symbol: 'GS', name: 'Goldman Sachs' },
      { symbol: 'MS', name: 'Morgan Stanley' },
      { symbol: 'SPGI', name: 'S&P Global' },
      { symbol: 'BLK', name: 'BlackRock' },
      { symbol: 'AXP', name: 'American Express' },
      { symbol: 'C', name: 'Citigroup' },
      { symbol: 'CB', name: 'Chubb' },
      { symbol: 'PNC', name: 'PNC Financial' },
      { symbol: 'USB', name: 'U.S. Bancorp' },
    ],
  },
  XLE: {
    etf: 'XLE',
    fullName: 'Energy',
    constituents: [
      { symbol: 'XOM', name: 'Exxon Mobil' },
      { symbol: 'CVX', name: 'Chevron' },
      { symbol: 'COP', name: 'ConocoPhillips' },
      { symbol: 'EOG', name: 'EOG Resources' },
      { symbol: 'SLB', name: 'SLB' },
      { symbol: 'MPC', name: 'Marathon Petroleum' },
      { symbol: 'OXY', name: 'Occidental' },
      { symbol: 'PSX', name: 'Phillips 66' },
      { symbol: 'PXD', name: 'Pioneer Natural Resources' },
      { symbol: 'VLO', name: 'Valero Energy' },
      { symbol: 'WMB', name: 'Williams' },
      { symbol: 'KMI', name: 'Kinder Morgan' },
      { symbol: 'OKE', name: 'ONEOK' },
      { symbol: 'DVN', name: 'Devon Energy' },
      { symbol: 'FANG', name: 'Diamondback Energy' },
    ],
  },
  XLV: {
    etf: 'XLV',
    fullName: 'Health Care',
    constituents: [
      { symbol: 'LLY', name: 'Eli Lilly' },
      { symbol: 'UNH', name: 'UnitedHealth' },
      { symbol: 'JNJ', name: 'Johnson & Johnson' },
      { symbol: 'ABBV', name: 'AbbVie' },
      { symbol: 'MRK', name: 'Merck' },
      { symbol: 'TMO', name: 'Thermo Fisher' },
      { symbol: 'ABT', name: 'Abbott' },
      { symbol: 'DHR', name: 'Danaher' },
      { symbol: 'ISRG', name: 'Intuitive Surgical' },
      { symbol: 'BMY', name: 'Bristol-Myers Squibb' },
      { symbol: 'PFE', name: 'Pfizer' },
      { symbol: 'AMGN', name: 'Amgen' },
      { symbol: 'GILD', name: 'Gilead' },
      { symbol: 'VRTX', name: 'Vertex' },
      { symbol: 'ZTS', name: 'Zoetis' },
    ],
  },
  XLY: {
    etf: 'XLY',
    fullName: 'Consumer Discretionary',
    constituents: [
      { symbol: 'AMZN', name: 'Amazon' },
      { symbol: 'TSLA', name: 'Tesla' },
      { symbol: 'HD', name: 'Home Depot' },
      { symbol: 'MCD', name: "McDonald's" },
      { symbol: 'NKE', name: 'Nike' },
      { symbol: 'LOW', name: "Lowe's" },
      { symbol: 'BKNG', name: 'Booking Holdings' },
      { symbol: 'TJX', name: 'TJX Companies' },
      { symbol: 'SBUX', name: 'Starbucks' },
      { symbol: 'CMG', name: 'Chipotle' },
      { symbol: 'MAR', name: 'Marriott' },
      { symbol: 'LULU', name: 'Lululemon' },
      { symbol: 'F', name: 'Ford' },
      { symbol: 'GM', name: 'GM' },
      { symbol: 'ORLY', name: "O'Reilly Automotive" },
    ],
  },
  XLI: {
    etf: 'XLI',
    fullName: 'Industrials',
    constituents: [
      { symbol: 'GE', name: 'GE Aerospace' },
      { symbol: 'CAT', name: 'Caterpillar' },
      { symbol: 'RTX', name: 'RTX Corp' },
      { symbol: 'HON', name: 'Honeywell' },
      { symbol: 'UPS', name: 'UPS' },
      { symbol: 'LMT', name: 'Lockheed Martin' },
      { symbol: 'DE', name: 'Deere & Company' },
      { symbol: 'BA', name: 'Boeing' },
      { symbol: 'GD', name: 'General Dynamics' },
      { symbol: 'UNP', name: 'Union Pacific' },
      { symbol: 'ADP', name: 'ADP' },
      { symbol: 'CSX', name: 'CSX' },
      { symbol: 'NOC', name: 'Northrop Grumman' },
      { symbol: 'TDG', name: 'TransDigm' },
      { symbol: 'WM', name: 'Waste Management' },
    ],
  },
  XLP: {
    etf: 'XLP',
    fullName: 'Consumer Staples',
    constituents: [
      { symbol: 'WMT', name: 'Walmart' },
      { symbol: 'PG', name: 'Procter & Gamble' },
      { symbol: 'COST', name: 'Costco' },
      { symbol: 'KO', name: 'Coca-Cola' },
      { symbol: 'PEP', name: 'PepsiCo' },
      { symbol: 'PM', name: 'Philip Morris' },
      { symbol: 'MO', name: 'Altria' },
      { symbol: 'MDLZ', name: 'Mondelez' },
      { symbol: 'CL', name: 'Colgate-Palmolive' },
      { symbol: 'TGT', name: 'Target' },
      { symbol: 'KMB', name: 'Kimberly-Clark' },
      { symbol: 'GIS', name: 'General Mills' },
      { symbol: 'SYY', name: 'Sysco' },
      { symbol: 'EL', name: 'Estée Lauder' },
      { symbol: 'DG', name: 'Dollar General' },
    ],
  },
  XLU: {
    etf: 'XLU',
    fullName: 'Utilities',
    constituents: [
      { symbol: 'NEE', name: 'NextEra Energy' },
      { symbol: 'SO', name: 'Southern Company' },
      { symbol: 'DUK', name: 'Duke Energy' },
      { symbol: 'SRE', name: 'Sempra' },
      { symbol: 'AEP', name: 'American Electric Power' },
      { symbol: 'EXC', name: 'Exelon' },
      { symbol: 'XEL', name: 'Xcel Energy' },
      { symbol: 'PCG', name: 'PG&E' },
      { symbol: 'ED', name: 'Consolidated Edison' },
      { symbol: 'WEC', name: 'WEC Energy' },
      { symbol: 'D', name: 'Dominion Energy' },
      { symbol: 'AEE', name: 'Ameren' },
      { symbol: 'PEG', name: 'Public Service Enterprise' },
      { symbol: 'EIX', name: 'Edison International' },
      { symbol: 'ES', name: 'Eversource Energy' },
    ],
  },
  XLB: {
    etf: 'XLB',
    fullName: 'Materials',
    constituents: [
      { symbol: 'LIN', name: 'Linde' },
      { symbol: 'APD', name: 'Air Products' },
      { symbol: 'SHW', name: 'Sherwin-Williams' },
      { symbol: 'FCX', name: 'Freeport-McMoRan' },
      { symbol: 'ECL', name: 'Ecolab' },
      { symbol: 'NEM', name: 'Newmont' },
      { symbol: 'DD', name: 'DuPont' },
      { symbol: 'NUE', name: 'Nucor' },
      { symbol: 'DOW', name: 'Dow Inc' },
      { symbol: 'PPG', name: 'PPG Industries' },
      { symbol: 'CTVA', name: 'Corteva' },
      { symbol: 'LYB', name: 'LyondellBasell' },
      { symbol: 'IFF', name: 'IFF' },
      { symbol: 'PKG', name: 'Packaging Corp' },
      { symbol: 'VMC', name: 'Vulcan Materials' },
    ],
  },
  XLRE: {
    etf: 'XLRE',
    fullName: 'Real Estate',
    constituents: [
      { symbol: 'PLD', name: 'Prologis' },
      { symbol: 'AMT', name: 'American Tower' },
      { symbol: 'EQIX', name: 'Equinix' },
      { symbol: 'PSA', name: 'Public Storage' },
      { symbol: 'WELL', name: 'Welltower' },
      { symbol: 'DLR', name: 'Digital Realty' },
      { symbol: 'O', name: 'Realty Income' },
      { symbol: 'AVB', name: 'AvalonBay' },
      { symbol: 'EQR', name: 'Equity Residential' },
      { symbol: 'VICI', name: 'VICI Properties' },
      { symbol: 'SBAC', name: 'SBA Communications' },
      { symbol: 'CCI', name: 'Crown Castle' },
      { symbol: 'EXR', name: 'Extra Space Storage' },
      { symbol: 'ARE', name: 'Alexandria Real Estate' },
      { symbol: 'BXP', name: 'Boston Properties' },
    ],
  },
  XLC: {
    etf: 'XLC',
    fullName: 'Communication Services',
    constituents: [
      { symbol: 'META', name: 'Meta' },
      { symbol: 'GOOGL', name: 'Alphabet' },
      { symbol: 'NFLX', name: 'Netflix' },
      { symbol: 'DIS', name: 'Disney' },
      { symbol: 'CMCSA', name: 'Comcast' },
      { symbol: 'T', name: 'AT&T' },
      { symbol: 'VZ', name: 'Verizon' },
      { symbol: 'TMUS', name: 'T-Mobile' },
      { symbol: 'CHTR', name: 'Charter Communications' },
      { symbol: 'EA', name: 'Electronic Arts' },
      { symbol: 'WBD', name: 'Warner Bros Discovery' },
      { symbol: 'TTWO', name: 'Take-Two' },
      { symbol: 'LYV', name: 'Live Nation' },
      { symbol: 'PARA', name: 'Paramount' },
      { symbol: 'FOX', name: 'Fox Corp' },
    ],
  },
  SMH: {
    etf: 'SMH',
    fullName: 'Semiconductors',
    constituents: [
      { symbol: 'NVDA', name: 'NVIDIA' },
      { symbol: 'TSM', name: 'TSMC' },
      { symbol: 'AVGO', name: 'Broadcom' },
      { symbol: 'ASML', name: 'ASML' },
      { symbol: 'AMD', name: 'AMD' },
      { symbol: 'QCOM', name: 'Qualcomm' },
      { symbol: 'INTC', name: 'Intel' },
      { symbol: 'MU', name: 'Micron' },
      { symbol: 'AMAT', name: 'Applied Materials' },
      { symbol: 'LRCX', name: 'Lam Research' },
      { symbol: 'MRVL', name: 'Marvell' },
      { symbol: 'NXPI', name: 'NXP Semiconductors' },
      { symbol: 'KLAC', name: 'KLA' },
      { symbol: 'MPWR', name: 'Monolithic Power' },
      { symbol: 'SNPS', name: 'Synopsys' },
    ],
  },
};
